name: Firestore Backup

on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Backup Repo
        uses: actions/checkout@v3
        with:
          repository: moroii69/TenShort-Backups
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Up Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate Firebase
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > firebase.json

      - name: Export Firestore Data
        run: firebase firestore:export ./backup --project your-firebase-project-id

      - name: Commit & Push Backup
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Automated Firestore Backup - $(date +'%Y-%m-%d')"
          git push origin main
